# Site Settings
lang: en
title: BhargavAchary.in
tagline: Just another not so ordinary engineer, creator, artist.
email:
description: >
  The personal website and blog of D K Bhargav Achary.
baseurl: "/blog-preview"
url: "https://bhargavachary.github.io"
permalink: /:year/:month/:day/:title.html
favicon: /images/favicon.png

paginate: 4
paginate_path: /page:num/

# Disqus Comments
disqus:
  shortname: bhargavacharyin

# Analytics
google_analytics: G-445636200

# Theme
remote_theme: chrisrhymes/bulma-clean-theme

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from
  - jekyll-remote-theme

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.txt
  - CHANGELOG.md
  - MIGRATION_README.md
  - old-site
  - products.md
  - _products
  - docs/products

# Sass configuration handled by remote theme

markdown: kramdown
highlighter: rouge
timezone: Asia/Calcutta

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      show_sidebar: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Bhargav Achary"
      layout: post
      show_sidebar: false
      comments: true

# Author information
author:
  name: Bhargav Achary
  avatar: /images/avatar.jpg
  bio: Just another not so ordinary engineer, creator, artist.
  location: Hyderabad, India

# Social links
social:
  facebook: https://facebook.com/BhargavAchary.github.io
  instagram: https://www.instagram.com/bhargav_achary
  twitter: https://twitter.com/bhargav_achary
  linkedin: https://www.linkedin.com/in/bhargavachary
  youtube: https://www.youtube.com/bhargavachary
  flickr: https://www.flickr.com/people/bhargav_achary
  soundcloud: https://soundcloud.com/bhargav-achary
